### ISSUE TITLE
APP Data collection policy

### ISSUE THREAD

**Issue by Woife5** [Woife5/DPP-documentation#2]
Die app sollte ein popup haben dass wir das kehr-verhalten von usern sammeln und für Produktverbesserungen verwenden.
Das popup soll "Zustimmen" und "Verweigern" buttons haben aber nur zustimmen funktioniert, sonst passiert nix.

evtl. verweigen button sehr klein und mit noch mehr popups bei klick?

**Comment by Rathalin** [comment]
Ich hab daweil einen Cookie-Disclaimer eingebaut, der genauestens erklärt, wie wir Cookies NICHT verwenden (um bei der Wahrheit zu bleiben). Der Accept-Button ist groß und am Anfang. Um den winzigen Decline-Button zu finden, muss bis nach unten gescrollt werden.

**Comment by Woife5** [comment]
hab wie besprochen noch das data-collection popup gemacht, i glaub das passt jetzt so 👍🏼
